backend:
  name: github
  repo: AliceLeRaptor/aurore-energetique
locale: "fr"
media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media
collections:
  - name: "cares"
    label: "Soins"
    folder: "src/cares"
    media_folder: ""
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Prix", name: "price", widget: "number" }
      - { label: "Description", name: "body", widget: "markdown" }
